### ISSUE TITLE
Not compatible with React 18

### ISSUE THREAD

**Issue by tolokoban** [probablyup/markdown-to-jsx#435]
First of all, I love this package!
It works fine with React 17.0.2, but cannot compile with React 18.0.0

We get this error message:

```
node_modules/markdown-to-jsx/dist/index.d.ts:53:73 - error TS2694: Namespace 'React' has no exported member 'Props'.

53         createElement: (tag: Parameters<CreateElement>[0], props: React.Props<any>, ...children: React.ReactChild[]) => JSX.Element;
                                                                           ~~~~~
```

**Comment by Chris112** [comment]
Quick bandaid to get around the build error is to add `"skipLibCheck": true` to your tsconfig

**Comment by tolokoban** [comment]
Good to know. Thanks!

**Comment by probablyup** [comment]
Oh hmm, I guess they must have changed the types. We can fix it for v8

**Comment by quantizor** [comment]
Fixed
