### ISSUE TITLE
Type error with v7.0.0

### ISSUE THREAD

**Issue by arivanandan** [probablyup/markdown-to-jsx#333]
```
TypeError: react__WEBPACK_IMPORTED_MODULE_0___default() is not a function
e
node_modules/markdown-to-jsx/dist/index.module.js:884
```

React version: 16.8.13

I'm simply trying it out so code looks something like

```
import { compiler } from 'markdown-to-jsx';
...
...
  return compiler('# Hello world!');
```
or 
```
import Markdown from 'markdown-to-jsx';
...
...
  return (
    <Markdown>
      {markdown}
    </Markdown>
  )
```
Works with release 6.11.4

**Comment by coreyward** [comment]
Ditto. Seeing `react___default(...) is not a function` with 7.0.0, even when just doing `compiler("hi")`.

**Comment by probablyup** [comment]
Hmm, if you're using the CJS version I think it's because `compiler` is added via `Object.assign` and not a named export. Can you use the ESM entry point?

**Comment by probablyup** [comment]
Also open to alternate implementations for https://github.com/probablyup/markdown-to-jsx/blob/master/index.cjs.tsx, I was mostly following the recommendations from `microbundle`

**Comment by coreyward** [comment]
@probablyup I'm not sure I follow. I'm using ESM style imports already. This happens with either `import Markdown from "markdown-to-jsx"` or `import { compiler } from "markdown-to-jsx"`, but not until you use the imported function. This is in the context of a Gatsby app in one case and a Sanity.io Studio in another—both are using Webpack.

**Comment by coreyward** [comment]
Hmm, I'm not sure what it's supposed to look like TBH. I just know that updating to 7.x in any context I'm used to using `markdown-to-jsx` in results in an error, but locking to the 6.x releases works fine.

**Comment by arivanandan** [comment]
Seems to work if I bundle index.tsx instead of index.cjs.tsx

**Comment by fastfedora** [comment]
Got the same error here. I was able to work around it by importing using:

```
import ReactMarkdown from 'markdown-to-jsx/dist/index.js';
```

In case it helps debugging, `index.umd.js` also worked, but `index.module.js` and `index.modern.js` generated the above error.

**Comment by probablyup** [comment]
Gotcha. Must be something to do with how microbundle packages things :/

**Comment by probablyup** [comment]
If anyone wants to take a stab at looking into it, I'd appreciate it.

**Comment by arivanandan** [comment]
Dunno the specifics but updating webpack makes it go away. Moved from 4.28.3 to the slightly higher minor version at 4.44.2 and it worked.
